### ISSUE TITLE
Hey, check this out

### ISSUE THREAD

**Issue by maximwebb** [benmandrew/ForwardVsDeferredRendering#1]
![image](https://user-images.githubusercontent.com/29152814/108103347-ba159200-7081-11eb-82cd-69e210aa96d4.png)

**Comment by benmandrew** [comment]
Excuse me @maximwebb please only post issues relating to the repo. Thank you.

I will be closing this issue now.

![2021_01_30_0zx_Kleki](https://user-images.githubusercontent.com/13054139/108199941-a3b91600-7115-11eb-93f6-f0b272ee55b2.png)
